# Generated by Django 4.2.13 on 2024-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opai', '0002_ppt_ppt_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppt',
            name='ppt_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
