# Generated by Django 4.2.13 on 2024-05-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opai', '0003_ppt_ppt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppt',
            name='status',
            field=models.CharField(default='loading', max_length=100),
        ),
    ]
