version: '3'

services:
  web: &web
    build: .
    image: gpt_slides
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      # - .:/app
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  celary: 
    <<: *web
    image: gpt_slides-celary
    command: >
      sh -c "
        celery --app=gpt_slides worker --loglevel=info"
    ports: []

  flower: 
    <<: *web
    image: gpt_slides-flower
    command: >
      sh -c "
        FLOWER_UNAUTHENTICATED_API=True celery -A gpt_slides --broker=redis://redis:6379/0 flower --port=5555 "
    depends_on:
      - redis
      - celary
    ports:
      - "5555:5555"
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge